export const ADD_TODO = 'add_todo'
export const RECEIVE_TODOS = 'receive_todos'
export const DELETE_TODO = 'delete_todo'
export const SELECT_ALL = 'select_all'
export const CLEAR_COMPLETE_TODOS = 'clear_complete_todos'